Issue 27 what spi
pappersverk/inky pull request #32
Opened 2019-07-26 13:44 UTC by lawik

Not sure if we have a good way of testing the chunking stuff since that's deep in the IO layer. Any thoughts?

Aside from that, would be good to have your eye on this before pushing it through. Probably makes sense to make 1.0.1 for this right?

2019-07-26 14:52 UTC, BrynjarM approved these changes
Tested and verified (ee68044fd3424cbd836034b8841229804e152f27) that it works  on my wHAT

2019-07-30 08:40 UTC, nyaray requested changes

2019-07-30 08:40 UTC, nyaray commented on lib/hal/rpiio.ex
> +  @spi_chunk_size 4096
Should be suffixed with `bits` or `bytes` for clarity of intent.

2019-07-30 08:40 UTC, nyaray commented on lib/hal/rpiio.ex
> +    spi_write(pins, data_or_command, :erlang.list_to_binary(values))
Does it not break tests that you added an unnecessary duplicated write to `dc`? Remove the GPIO write if this is going to rely on the later clause via the recursive call.

2019-07-30 08:40 UTC, nyaray commented on lib/hal/rpiio.ex
> +        end
* lines 108-117 should probably be in a separate function, named something like `spi_write_chunked`
* `x` should be named `chunk_index` and `parts`, `chunk_count`

2019-07-30 08:40 UTC, nyaray commented on lib/hal/rpihal.ex
> +  # Set voltage of VSH and VSL on Yellow device
The comment should probably be copied to the red what function.

2019-08-03 19:10 UTC, nyaray commented on lib/hal/rpiio.ex
> +    spi_write(pins, data_or_command, :erlang.list_to_binary(values))
My bad, upon closer inspection, we didn't have a test for that.

2019-08-04 16:23 UTC, nyaray commented on lib/hal/rpihal.ex
> +  # Set voltage of VSH and VSL on Yellow device
✓

2019-08-04 16:29 UTC, nyaray approved these changes

2019-08-04 19:39 UTC, nyaray commented
@BrynjarM would you mind verifying the latest commit on this branch?

Since you've got a wHAT, I'll also be asking you to check out a performance improvement I've been working at some point in the not too distant future, if that's ok!

2019-08-08 13:12 UTC, BrynjarM commented
@nyaray sorry for the delay, tested fe9bab3e268605ee39c54e097b31576915f94765 and it works on my wHAT

Sure, just ping me when the performance improvements are ready

2019-08-08 20:37 UTC, merged

2020-01-21 22:25 UTC, JonRowe commented
Any chance of releasing this 😬 (sorry to ask but I ran into the what bug too and then noticed it was fixed here 😂 )

2020-01-22 05:39 UTC, lawik commented
Ah, I'll take a look :)